const $=id=>document.getElementById(id), fmt=v=>v===null?'정의되지 않음':v.toFixed(4);
let points=ORIGINAL_DATA.map(r=>[r[5],r[6]]), models;
function restore(){$('dataInput').value=ORIGINAL_DATA.map(r=>r[5]+','+r[6]).join('\n');}
function render(){models=fitRegression(points);$('count').textContent=models.n+'개 관측값';$('metrics').innerHTML=[['선형 회귀',models.linear],['2차 회귀',models.quadratic]].map(([name,m])=>`<div class="metric"><strong>${name}</strong><code>Y = ${fmt(m.a)}X² ${m.b<0?'−':'+'} ${fmt(Math.abs(m.b))}X ${m.c<0?'−':'+'} ${fmt(Math.abs(m.c))}</code><div class="numbers"><span>R² <b>${fmt(m.r2)}</b></span><span>RMSE <b>${fmt(m.rmse)}</b></span></div></div>`).join('');draw();predict();}
function draw(){const xs=points.map(p=>p[0]),xmin=Math.min(...xs),xmax=Math.max(...xs),curves=Array.from({length:101},(_,i)=>xmin+(xmax-xmin)*i/100),ys=[...points.map(p=>p[1]),...curves.flatMap(x=>[models.linear.predict(x),models.quadratic.predict(x)])],lo=Math.min(0,...ys),hi=Math.max(...ys),pad=(hi-lo||1)*.08,ymin=lo-pad,ymax=hi+pad,X=x=>65+(x-xmin)/(xmax-xmin)*700,Y=y=>350-(y-ymin)/(ymax-ymin)*320;let svg='';for(let i=0;i<=5;i++){const y=ymin+(ymax-ymin)*i/5;svg+=`<line x1="65" y1="${Y(y)}" x2="765" y2="${Y(y)}" stroke="#e1e8ef"/><text x="54" y="${Y(y)+5}" text-anchor="end" fill="#607387" font-size="14">${y.toFixed(1)}</text>`;}for(let i=0;i<=5;i++){const x=xmin+(xmax-xmin)*i/5;svg+=`<text x="${X(x)}" y="375" text-anchor="middle" fill="#607387" font-size="14">${x.toFixed(3)}</text>`;}svg+=points.map(([x,y])=>`<circle cx="${X(x)}" cy="${Y(y)}" r="3" fill="#8093a8" opacity=".45"><title>X=${x}, Y=${y}</title></circle>`).join('');for(const [m,color] of [[models.linear,'#246bdf'],[models.quadratic,'#ce631f']])svg+=`<path d="${curves.map((x,i)=>(i?'L':'M')+X(x)+' '+Y(m.predict(x))).join(' ')}" stroke="${color}" stroke-width="3" fill="none"/>`;svg+='<text x="415" y="409" text-anchor="middle" fill="#607387" font-size="14">프루드 수 X</text>';$('chart').innerHTML=svg;}
function predict(){const raw=$('predictX').value,x=Number(raw);if(!raw.trim()||!Number.isFinite(x)){$('prediction').textContent='유효한 숫자를 입력하세요.';return;}const a=models.linear.predict(x),b=models.quadratic.predict(x),xs=points.map(p=>p[0]);$('prediction').textContent=`선형: ${fmt(a)} / 2차: ${fmt(b)}`+(x<Math.min(...xs)||x>Math.max(...xs)?' · 관측 범위 밖의 외삽입니다.':'')+(a<0||b<0?' · 음수 예측은 실제 저항으로 해석할 수 없습니다.':'');}
$('predict').onclick=predict;$('predictX').oninput=predict;$('reset').onclick=()=>{restore();points=ORIGINAL_DATA.map(r=>[r[5],r[6]]);$('error').textContent='';render();};
$('analyze').onclick=()=>{try{const parsed=$('dataInput').value.trim().split(/\n/).map((line,i)=>{const v=line.trim().split(/[,\t]/).map(s=>s.trim());if(v.length!==2||v.some(s=>!s||!Number.isFinite(Number(s))))throw Error((i+1)+'번째 줄을 X,Y 숫자 형식으로 입력하세요.');return v.map(Number);});if(parsed.length>5000)throw Error('최대 5,000개 행을 입력할 수 있습니다.');fitRegression(parsed);points=parsed;render();$('error').textContent='';}catch(e){$('error').textContent=e.message;}};
let runningWorker=null,runningTimer=null;
$('run').onclick=()=>{if(runningWorker)runningWorker.terminate();clearTimeout(runningTimer);const source=$('code').value,blob=new Blob([`onmessage = async function(e) { try { const predict = new Function(e.data.code + '\\n; return predict;')(); const values=[0.125,0.3,0.45].map(x=>{const y=predict(x,e.data.model);if(!Number.isFinite(y))throw Error('유한한 숫자를 반환해야 합니다.');return {x,y};}); postMessage({values}); } catch(err) { postMessage({error:err.message}); } };`],{type:'text/javascript'}),url=URL.createObjectURL(blob),worker=new Worker(url);URL.revokeObjectURL(url);runningWorker=worker;$('codeResult').textContent='실행 중…';const stop=()=>{worker.terminate();clearTimeout(runningTimer);if(runningWorker===worker)runningWorker=null;};runningTimer=setTimeout(()=>{stop();$('codeResult').textContent='실행 시간이 2초를 초과했습니다. 반복문을 확인하세요.';},2000);worker.onmessage=e=>{stop();$('codeResult').textContent=e.data.error?'오류: '+e.data.error:e.data.values.map(v=>`X=${v.x.toFixed(3)} → Y=${v.y.toFixed(4)}`).join('\n');};worker.onerror=e=>{stop();$('codeResult').textContent='오류: '+e.message;};const {a,b,c}=models.quadratic;worker.postMessage({code:source,model:{a,b,c}});};restore();render();
